[tool.poetry]
name = "final-project"
version = "0.1.0"
description = ""
authors = ["Bakhtiyar Ospanov <bakhtiyar@qtap.kz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
