# Generated by Django 4.2.7 on 2023-11-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('first_answer', models.TextField()),
                ('second_answer', models.TextField()),
                ('third_answer', models.TextField()),
                ('fourth_answer', models.TextField()),
                ('correct_answer', models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')])),
            ],
        ),
    ]
