# Generated by Django 4.2.7 on 2023-11-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='first_answer',
            new_name='a_answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='fourth_answer',
            new_name='b_answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='second_answer',
            new_name='c_answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='third_answer',
            new_name='d_answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A answer'), ('B', 'B answer'), ('C', 'C answer'), ('D', 'D answer')], max_length=1),
        ),
    ]
